//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUserManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressDetail
    {
        public int AddressID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public Nullable<int> Pincode { get; set; }
        public int CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual State State { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
    }
}
