//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentList
    {
        public int DocumentID { get; set; }
        public int ObjectID { get; set; }
        public int ObjectType { get; set; }
        public int DocumentType { get; set; }
        public string DocumentNameOnDisk { get; set; }
        public string DocumentOriginalName { get; set; }
    }
}
